version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_103
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    container_name: postgres_db